# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jun Hyeok, Jeong
title: Undergraduate Student
email: 2023011929@gnu.ac.kr
website: github.com/JJUNHYEOK

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  JJUNHYEOK
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: popcornwithcola
# linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_2519.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi ! My name is Jun Hyeok. I am an undergraduate intern at the <mark><a href="https://bdss.gnu.ac.kr/" target="_blank">BigData System Software Lab</a></mark> at GNU, advised by <mark><a href="https://scholar.google.co.kr/citations?user=bUZe0WwAAAAJ&hl=ko&oi=ao" target="_blank">Jaeho Kim</a></mark>. I am interested in efficient data storage which is in high demand these days, especially Solid-State-Drive (SSD). And I also use several algorithms about ML and CP, for testing device reliability and lifespan. Previously, I am studying with B.S. from GNU in Aerospace and Software engineering(not the double-major).

  I am most skilled in: <mark>Python</mark>, <mark>C</mark> and <mark>Football</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Lab Presentation
        link: github.com/JJUNHYEOK/LAB
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          🔗 [Coding for SSD](https://github.com/JJUNHYEOK/LAB/blob/main/codingforSSD_1.pdf)  
          🔗 [Applying K-means Algorithm on Hotness Classification](https://github.com/JJUNHYEOK/LAB/blob/main/HotnessClassificaation.pdf)  
          🔗 [Simple SSD Simulator Implementation](https://github.com/JJUNHYEOK/LAB/tree/main/ssd_simulator_simple)
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KSC 2024
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Korea Software Congress 2024
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gyeonsang National University
        caption: 2023 -
        sub_title: Aerospace & Software Engineering (More focused on SW Engineering including domain CS Knowledges.)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Will be updated soon as possible

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Football
      - Competitive Programming (<mark><a href="https://solved.ac/profile/spacehyuck" target="_blank">BOJ Silver III</a></mark>)
      - Anything else ..? I will put it when I think of it.
# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

collections:
  posts:
    output: true
permalink : pretty


